### ISSUE TITLE
Unable to load JS bundle - Android

### ISSUE THREAD

**Issue by satvikmaker** [alinz/example-react-native-redux#10]
Hi,

I really wanted to try out this example. It's my first step towards redux. But, I get the following error all the time-

My terminal-

![bundle-unable-to-reload](https://cloud.githubusercontent.com/assets/1252941/12007368/6ab3e8c0-ac27-11e5-8e41-3e202611de50.png)

My Mobile-

![bundle-unable-to-reload-mobile](https://cloud.githubusercontent.com/assets/1252941/12007370/9272adba-ac27-11e5-907e-76910617052d.png)

All other react native apps are working fine.

I did the following-
1. Cloned this repo
2. npm install
3. react-native start
4. react-native run-android

Then, JS bundle reload fails at like 99% step. But, react-native run-android (app installation) is successful.

Any idea what's the reason? What am I missing?

**Comment by sampurcell93** [comment]
+1 - I also ran npm clean which did not seem to do anything

EDIT: Meant to post `npm run clean` instead of just `npm clean`... sorry!

**Comment by sampurcell93** [comment]
Actually, I just got mine to work... Make sure you restart your packager process, then try rebuilding with `react-native run-android`. Worked for me!

**Comment by satvikmaker** [comment]
Thanks @sampurcell93 . But, still no success :(

**Comment by alinz** [comment]
@bozzmob Thanks for filing this issue. One thing that you have missed is `npm run clean`.

so do this,
1. Cloned this repo
2. npm install
3. npm run clean
4. react-native start
5. react-native run-android

Let me know if you still have a problem.

**Comment by alinz** [comment]
One other thing, before running `react-native start`, run `lsof -t -i:8081` in your bash. Maybe another process still using that port and you are being served by that process. Kill all of those process and try running `react-native start` again.

**Comment by satvikmaker** [comment]
It worked after `npm run clean` Thanks @alinz :+1:  ! This is such a perfect example to start off with redux!

**Comment by alinz** [comment]
@bozzmob Awesome! glad that it helps. Good luck
