### ISSUE TITLE
Fresh clone is erroring when run

### ISSUE THREAD

**Issue by jolyonruss** [alinz/example-react-native-redux#11]
Steps to reproduce:
- clone repo
- npm install
- open /ios/Counter.xcodeproj in Xcode
- run the app in Xcode
- build is successful & Simulator opens
- app errors with the following

EventPluginRegistry: Cannot inject event plugin ordering more than once. You are likely trying to load more than one copy of React.

Any idea what might be causing this?

**Comment by alinz** [comment]
After npm install, you should run npm run clean. I have already mentioned it in Readme file

**Comment by jolyonruss** [comment]
@alinz Please feel free to delete this issue, I was having a really frustrating evening and everything seemed to be broken - it's all good now. Thanks also for creating this example project it's been invaluable to see React Native and Redux in situ.

**Comment by alinz** [comment]
@jolyonruss Glad that you have managed to fix it. Keep posting issue and I will try to help you out.
