### ISSUE TITLE
example showing thunk usage would be appreciated

### ISSUE THREAD

**Issue by tomprogers** [alinz/example-react-native-redux#17]
Think is one of the weirder parts of an already-weird package of techs. An example is welcome showing not just how to install thunk, but how it fits into the process of making async calls and updating the store once those calls return.

**Comment by tsvetann** [comment]
+1

**Comment by holyxiaoxin** [comment]
+1

**Comment by cablegunmaster** [comment]
This would always make a good call +1.

**Comment by alinz** [comment]
I will update the example to reflect this request, stay tuned.

**Comment by alinz** [comment]
@tomprogers @tsvetann @holyxiaoxin and @cablegunmaster, check Counters example. It has a lot of good stuff including thunk!
