### ISSUE TITLE
Unable to load on android

### ISSUE THREAD

**Issue by csterritt** [alinz/example-react-native-redux#18]
Hi,

Did a `git clone`, cd to Counter, `npm install`, then `react-native run-android`.

I got no errors from either the install or run.

However, when the app starts, it immediately fails with the message: "RCTNetworking sendRequest got 7 arguments, expect 6".

Using node version 5.5.0, npm version 3.3.12.

Thanks!

**Comment by dangkaka** [comment]
Hi,
Same error here. Do you know how to fix it?

**Comment by csterritt** [comment]
Hey @dangkaka -- I haven't found a solution, but I did find this project:

https://github.com/bartonhammond/snowflake

Which runs fine on my tablet (with one minor issue that the checkbox image/icon/font/whatever) doesn't display correctly.  But it works!

**Comment by alinz** [comment]
@csterritt This is very wired. I have tested with mine. it works perfectly on both iOS and android. 

My setup is `npm 3.7.1`, `node v5.5.0` and watchman `4.1.0`.

Also can you check maybe one of the npm modules returns an error during installation. `npm 3.x` has a new way of displaying errors.

Also I have upgraded the project to support react-native `0.21.0` and redux `4.4.0`.

**Comment by csterritt** [comment]
Hi @alinz -- I removed the old directory, re-downloaded from github, did an `npm3 install`, and it installed and worked fine!  Thanks!
