### ISSUE TITLE
Error:  Unable to resolve module while Adding a new package 

### ISSUE THREAD

**Issue by RV2013** [alinz/example-react-native-redux#19]
Hi,

First of all thanks for such a nice source code which is up to date to get started with Redux on top of react native.Here are the steps to re-produce the issue.
1. Download the source code from repository
2. run npm install through terminal staying at Project Directory Root
3. Launch the app through XCode. All works fine and counter example is shown up.
4. Now I added another package with this command 'npm install react-native-grid-view' . again staying at Project's Root Directory
5. Package installed successfully. Created a new JS file and imported the package using bothy 2 options shown below : 
   import Gridview from 'react-native-grid-view';
   and 
   var GridView  = require ('react-native-grid-view');

and I got the below error 

Unable to resolve module react-native-grid-view from /Users/<username>/Documents/example-react-native-redux-master/Counter/app/components/Catalogue-Grid-View.js: Invalid directory /Users/node_modules/react-native-grid-view

Please help me as I have to use few more 3rd party components and packages ........

One more thing. I also observed that the package structure inside node_modules is a serial one and there are lot other packages which are not generally seen inside react_native package.

**Comment by alinz** [comment]
@RV2013 have you restarted the packager? every time you add a new module, you should restart the packager. Also, when you installing the any module, use --save flag to add it to your `package.json`. You might install that one globally since it tries to locate the file from `/Users/node_modules/react-native-grid-view` which is not inside the example-react-native-redux folder.

**Comment by alinz** [comment]
@RV2013 did you get it resolve? if so what was it?

**Comment by alinz** [comment]
closing ticket. reopen with more details.
