### ISSUE TITLE
Don't use decorators

### ISSUE THREAD

**Issue by gaearon** [alinz/example-react-native-redux#2]
You can avoid the need for patching by not using decorators.
We don't use them in official Redux examples anymore, either.

**Comment by alinz** [comment]
Good to know. Thanks, I will update the code and doc

**Comment by shaikhussian** [comment]
@alinz in this project you are using .babelrc file,did i need to create separately or it will come with package,Is there any package like that.

**Comment by alinz** [comment]
it will come with the package. Just clone the project. and run npm install.

**Comment by alinz** [comment]
@gaearon Thanks, I think we are forced to not use Decorator anyway in react-native. One thing we notice that redux has some .babelrc inside the project which causes Babel 6 in react-native fails. It would be good if you can remove this from redux and react-redux.
