### ISSUE TITLE
How to pass more than one state?

### ISSUE THREAD

**Issue by varqasim** [alinz/example-react-native-redux#20]
So in [/Counter/app/containers/counterApp.js](https://github.com/alinz/example-react-native-redux/blob/master/Counter/app/containers/counterApp.js) you're passing just one state which is `count` how to pass more than one state so that let's say in[ /Counter/app/reducers/counter.js](https://github.com/alinz/example-react-native-redux/blob/master/Counter/app/reducers/counter.js) I would have more than one initial state that I can play with:

```
const initialState = {
  count: 0,
  score: 0,
  name: "",
};
```

**Comment by alinz** [comment]
@qasimalbaqali,you have to create 2 things. action and reducer function.

``` js
import * as types from '../actions/actionTypes';

const initialState = {
  count: 0,
  name: ''
};

export default function counter(state = initialState, action = {}) {
  switch (action.type) {
    case types.INCREMENT:
      return {
        ...state,
        count: state.count + 1
      };
    case types.DECREMENT:
      return {
        ...state,
        count: state.count - 1
      };
    case types.UPDATE_NAME:
      return {
        ...state,
        name: action.value
      }
    default:
      return state;
  }
}
```

in actionTypes.js

``` js
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const UPDATE_NAME = 'UPDATE_NAME';
```

finally add the action

``` js
import * as types from './actionTypes';

export function increment() {
  return {
    type: types.INCREMENT
  };
}

export function decrement() {
  return {
    type: types.DECREMENT
  };
}

export function updateName(name) {
  return {
    type: types.UPDATE_NAME,
    value: name
  };
}
```

remember, actions can accept and send as many arguments. They can read the state but they can't change the state. Action can be sync or async operations.

reducer is always sync. they can read and they return a new version of state.

cheers,

**Comment by varqasim** [comment]
Thank you! That cleared a lot of stuff for me. One more question I'm trying to do a fetch() POST request, and in my understanding I have to do it in the reducer? So I am trying to change the state via fetch request, and then trying to set the state with the response. How to do it correctly, I can't seem to figure out how to change the states value. Any help would be highly appreciated :+1:

**Comment by alinz** [comment]
@qasimalbaqali all the async call should be done inside action. if action returns a function, it tells the redux that this action is async operation and redux will pass you dispatch as first argument. So lets say I want to call a get a number from server side.

``` js
export function increment() {
  return (dispatch, getState) => {
    fetch("http://localhost:8080/number").then((resp)=>{
        dispatch({
          type: types.INCREMENT,
          value: resp
        });
    });
  };
}
```

You should not do any async calls, including fetch, setTimeout, ... inside reducer. Reducers are sync operation.

**Comment by varqasim** [comment]
Makes sense! Thank you so much for your help and time.
