### ISSUE TITLE
"Store does not have a valid reducer ..."

### ISSUE THREAD

**Issue by gpmcadamold** [alinz/example-react-native-redux#21]
I'm getting the following error after a fresh checkout and build:

![image](https://cloud.githubusercontent.com/assets/1332361/13904393/f2670cc8-ee96-11e5-8402-d26bdbc86166.png)

> console.error: "Store does not have a valid reducer. Make sure the argument passed to combineReducers is an object whose values are reducers."

**Comment by alinz** [comment]
@gpmcadam have you install all the modules by calling `npm install`? make sure that you are using `npm 3.x`. Also these type of errors showing if you don't set the initial state. In my example, [here](https://github.com/alinz/example-react-native-redux/blob/master/Counter/app/reducers/counter.js#L7) what I set the initialState. Double check again and let me know if you still have this issue. 

can you also send me your info about node version and npm version.

**Comment by alinz** [comment]
@gpmcadam I have written another example, check that one and see if that works. reopen this issue if you still have problem

**Comment by smooJitter** [comment]
I'm getting the same error and I am using the code you mention above.  sort of odd.
