### ISSUE TITLE
Will be more helpful if there is some data posting and fetching in react native-redux

### ISSUE THREAD

**Issue by karthickvkumar** [alinz/example-react-native-redux#22]
Hi @alinz , thanks for this awesome counter example. Its helps alot in learning React native - Redux, If you find some time make a sample app on react native - redux on Network request (ie. data fetching and posting to local server) It would be more helpful.

Thanks in Advance

**Comment by alidawud** [comment]
+1

**Comment by alinz** [comment]
I will update the example soon. Stay tuned

**Comment by karthickvkumar** [comment]
thanks @alinz
