### ISSUE TITLE
Reducer/dispatcher extending.

### ISSUE THREAD

**Issue by cablegunmaster** [alinz/example-react-native-redux#24]
How to make this with multiple states? Or should I make 1 master state object and add everything to it?
Like state.master? I am almost grasping the complete picture but missing a few lines in my head to this context.  whats the most common way to grasp this idea?

```
export default connect(state => ({
    state: state.counter
  }),
  (dispatch) => ({
    actions: bindActionCreators(counterActions, dispatch)
  })
)(CounterApp);
```

Trying to make new modules for the first time with redux.

**Comment by alinz** [comment]
@cablegunmaster I have created another example to demonstrate it.
