### ISSUE TITLE
Projects not running.

### ISSUE THREAD

**Issue by nschurmann** [alinz/example-react-native-redux#26]
After cloning this repo and executing npm i i get this error on the iOS emulator:

<img width="371" alt="screen shot 2016-05-12 at 1 16 21 pm" src="https://cloud.githubusercontent.com/assets/5099344/15221924/d2399d0e-1843-11e6-8b79-149321f80b9c.png">

**Comment by alinz** [comment]
I have just did this and I got no error

``` bash
cd Counters
npm i
react-native run-ios
```

can you tell me your node version, npm version?

**Comment by alinz** [comment]
I'm closing this ticket since it is working on my side and nobody else was reporting this issue.

**Comment by zengyanzi** [comment]
could you tell me how do you solve this problem, please?
I have the same issue now.
Thanks in advance

**Comment by alinz** [comment]
@zengyanzi I have just revisited the Counters code and I have upgraded and fixed couple of issues there. Just clone the project, if you have `yarn` just call `yarn` inside `Counters`. It should be fully functional after that. Please let me know if you still have some problem running it.
