### ISSUE TITLE
Changes in Counter code, not reflected in app.

### ISSUE THREAD

**Issue by andwaredev-zz** [alinz/example-react-native-redux#28]
Hi,

I'm trying to make changes and edit the code base for the Counter app. I am able to run it successfully in Simulator (iPhone 6 iOS 9.3). However, it appears to be reading from an old build and nothing else, because any changes I make to the code even as simple as commenting out the line `AppRegistry.registerComponent('Counter', () => App);` in `index.ios.js` are not reflected in the app running on the Simulator. Refreshing, or re-running the app have no effect. 

Any guidance would be helpful here, I figure I'm just missing something that should be obvious.

**Comment by alinz** [comment]
@andrew-ware for performance reason, react-native caches some files, instead of running your dev server as `react-native start`, do this way `react-native start -- --reset-cache`. This might help. Let me know if this works or not.

**Comment by andwaredev-zz** [comment]
@alinz Yes, awesome, `react-native start -- --reset-cache` worked for me! I had previously been running `react-native run-ios` which I guess was just running the build that was included in the repo when I cloned it originally. Thanks!

**Comment by alinz** [comment]
@andrew-ware closing this.
