### ISSUE TITLE
Modules in the real app

### ISSUE THREAD

**Issue by zubko** [alinz/example-react-native-redux#29]
Thanks for the great example, esp for the concept of modules!

In the real apps do you make 1 module per screen or per common group of functionality?
Like, will you make modules Intro, Login, Signup, RecoverPassword, or will it be 1 module Onboarding?

How would you structure the code for navigation? Like a module which manages all other modules?

**Comment by alinz** [comment]
@zubko the question that you should ask is would I use `RecoverPassword` some where else in my app other than login? if yes, then you should create a module out of it which contains its own actions and store.

in terms of navigation, I would create a module per scene. but again there is no silver bullet. You have to experiment and as you progress, always ask your self will I need this some where else.
