### ISSUE TITLE
"RCTBundleURLProvider.h"

### ISSUE THREAD

**Issue by drgoof** [alinz/example-react-native-redux#31]
It is giving me the issue saying that "RCTBundleURLProvider.h" not found.

Help needed i know i am doing something wrong here.

Thanks

**Comment by alinz** [comment]
@drgoof can you fetch from master and `rm node_module` and do `npm install` and then try again to see if the error goes away. Let me know

**Comment by alinz** [comment]
The new code pushed to master branch should fix this problem because `RCTBundleURLProvider.h` was added recently. Try it and if it doesn't work reopen the ticket.
