### ISSUE TITLE
When I run the demo,it only crash on Android phone

### ISSUE THREAD

**Issue by easyli** [alinz/example-react-native-redux#39]
I can't run Counters on my Android phone , but can run it on ios Simulator.

I follow  #10 to fix it ,but still can't open the Counters App.

Could you help me ?

**Comment by eugen35** [comment]
I have the same problem... Could you help me, too ) ?
PS Clean project (react-native init myapp && cd myapp && react-natin run-android) is working for me
`FAILURE: Build failed with an exception.
                            
* Where:                    
Build file 'C:\Users\moshchanskiy\AndroidStudioProjects\Counter\android\app\build.gradle' line: 1
                            
* What went wrong:          
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.2 is required. Current version is 2.10. If using the gradle wrapper, try editing the distributionUrl in C
:\Users\moshchanskiy\AndroidStudioProjects\Counter\android\gradle\wrapper\gradle-wrapper.properties to gradle-2.2-all.zip
`

**Comment by easyli** [comment]
There are two demos . I can't run Counters .   
You can fix according to the wrong .   
Edit gradle-wrapper.properties , modify gradle-2.2-all.zip to gradle-2.10-all.zip   
Then try again.

**Comment by eugen35** [comment]
Hi! Thank you for answer! But i didnt try it.
**For now i found the way:**
```
1. react-native init Counter
2. cd Counter
3. npm i redux, react-redux, redux-thunk,redux-actions --save
4. //copy folder 'app' from your example in inited project
5. //copy files index.android.js and index.ios.js from your example in inited project
6. react-native run-android
```
**All works!!)**

**Comment by eugen35** [comment]
and about your answer: where can i find gradle-wrapper.properties?

**Comment by easyli** [comment]
.\Counter\android\gradle\gradle-wrapper.properties

**Comment by eugen35** [comment]
My Error^
What went wrong:          
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
   > Gradle version 2.2 is required. Current version is 2.10. If using the gradl
dle\wrapper\gradle-wrapper.properties to gradle-2.2-all.zip

**Comment by eugen35** [comment]
In my grandle.wrapper.properties:
#Wed Aug 24 16:23:50 IDT 2016
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip

**Comment by eugen35** [comment]
It doesnt work.
Then if i change to distributionUrl=https://services.gradle.org/distributions/gradle-2.2-all.zip
It stil doesn work

**Comment by alinz** [comment]
@easyli I have just revisited the Counters code base. It should be fully working now on both android and ios devices. Please try again and let me know. I will close this issue but feel free to open it again if you still have the issue.
