### ISSUE TITLE
When I run the demo,it only crash.

### ISSUE THREAD

**Issue by Obooman** [alinz/example-react-native-redux#6]
the dependency "react-native" is private(git+ssh),so I replace it to public type (https://)
Then I run npm install,everything is OK.Then I make the patch,just follow the steps.

Xcode Error:
![xcode error](https://cloud.githubusercontent.com/assets/9863282/11607114/89b50320-9b75-11e5-82a8-d1f3bf5d5ae4.png)

I guess it's because of the react-native version.
http://badge.fury.io/js/react-native
it's 0.16.0

I found latest version above.Can you help me with this😭

**Comment by alinz** [comment]
Going to update both React and redux. thanks for that, once I have updated the example I will let you know

**Comment by alinz** [comment]
@Obooman, I have updated everything inside the repo, please have a look and reopen this issue if you still have the same problem.

**Comment by Obooman** [comment]
Now it runs well,thanks for your awesome example
